name: AuraProject CI/CD to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Starting CI/CD Deployment Pipeline..."
          cd ~/AuraProject
          git config pull.rebase false
          git fetch origin main
          git reset --hard origin/main
          chmod +x deploy.sh
          ./deploy.sh